package com.retailshop.enums;

public enum WhatsAppBotIntent {
    WELCOME_MENU,
    BROWSE_CATEGORIES,
    SEARCH_PRODUCTS,
    PRODUCT_DETAILS,
    PRODUCT_RECOMMENDATION,
    OFFERS_AND_COUPONS,
    ORDER_HISTORY,
    LATEST_ORDER,
    ORDER_DETAILS,
    TOTAL_ORDER_VALUE,
    ORDER_COUNT,
    DELIVERY_STATUS,
    PAYMENT_STATUS,
    REFUND_STATUS,
    REORDER,
    ACCOUNT_HELP,
    CART_CHECKOUT_HELP,
    AGENT_HANDOFF,
    FALLBACK
}
